import type {
  WorkerProfile,
  AgentProfile,
  InstructorProfile,
  CustomerProfile,
  Order,
  TrainingCourse,
  CommissionRule,
  PointRule,
  CreditRule,
  DashboardStats,
  SettlementRecord,
  ReferralRecord,
  ResumeReviewRecord,
  JobType,
  Review,
  Role,
  PlatformInfo,
  ModuleConfig,
  TextConfig,
  SystemSettings,
  LeadStatus,
} from './types';

// ==================== 仪表盘 ====================
export const mockDashboardStats: DashboardStats = {
  totalAgents: 28,
  totalWorkers: 156,
  totalOrders: 423,
  totalRevenue: 856000,
  monthlyOrders: 67,
  monthlyRevenue: 142500,
  pendingReviews: 5,
  avgCreditScore: 87.3,
};

// ==================== 阿姨数据 ====================
export const mockWorkers: WorkerProfile[] = [
  {
    id: 'w001',
    name: '王秀兰',
    age: 45,
    gender: '女',
    origin: '安徽合肥',
    photo: '',
    phone: '13800005678',
    idCard: '3401****1234',
    jobTypes: ['月嫂', '育儿嫂'],
    experienceYears: 8,
    specialties: ['新生儿护理', '月子餐', '催乳'],
    certifications: ['高级月嫂证', '育婴师证'],
    expectedSalaryMin: 12000,
    expectedSalaryMax: 15000,
    status: 'available',
    availableDate: '2026-06-15',
    creatorId: 'a001',
    creatorName: '张丽华',
    creatorRole: 'agent',
    creatorCommissionRate: 30,
    maintainerId: 'a001',
    maintainerName: '张丽华',
    maintainerCommissionRate: 10,
    creditScore: 95,
    deposit: 300,
    points: 48,
    creditRecords: [
      { id: 'cr001', event: '获得客户好评', scoreChange: 2, createdAt: '2026-05-20' },
      { id: 'cr002', event: '获得客户好评', scoreChange: 2, createdAt: '2026-05-10' },
    ],
    trainingRecords: [
      { id: 'tr001', courseName: '高级月嫂技能提升', instructorName: '李敏', score: 92, passed: true, completedAt: '2026-04-15' },
    ],
    reviews: [
      { id: 'r001', type: 'customer', sourceRole: 'customer', reviewerName: '刘女士', reviewerRole: '客户', rating: 5, content: '非常专业，照顾宝宝很细心', hidden: false, createdAt: '2026-05-18' },
      { id: 'r002', type: 'agent', sourceRole: 'agent', reviewerName: '张丽华', reviewerRole: '经纪人', rating: 4, content: '工作认真，客户反馈好', hidden: false, createdAt: '2026-05-15' },
      { id: 'r003', type: 'instructor', sourceRole: 'instructor', reviewerName: '李敏', reviewerRole: '讲师', rating: 5, content: '培训期间学习态度端正，技能掌握好', hidden: false, createdAt: '2026-04-15' },
    ],
    createdAt: '2026-03-10',
    updatedAt: '2026-05-20',
    resumeReviewStatus: 'approved',
  },
  {
    id: 'w002',
    name: '李大姐',
    age: 38,
    gender: '女',
    origin: '湖南长沙',
    photo: '',
    phone: '13900002345',
    idCard: '4301****5678',
    jobTypes: ['保姆', '老人护理'],
    experienceYears: 5,
    specialties: ['老人照护', '做饭', '家务'],
    certifications: ['家政服务员证'],
    expectedSalaryMin: 7000,
    expectedSalaryMax: 9000,
    status: 'busy',
    availableDate: '2026-08-01',
    creatorId: 'a002',
    creatorName: '王建国',
    creatorRole: 'agent',
    creatorCommissionRate: 30,
    creditScore: 88,
    deposit: 200,
    points: 35,
    creditRecords: [
      { id: 'cr003', event: '获得客户好评', scoreChange: 2, createdAt: '2026-05-01' },
    ],
    trainingRecords: [],
    reviews: [
      { id: 'r004', type: 'customer', sourceRole: 'customer', reviewerName: '赵先生', reviewerRole: '客户', rating: 4, content: '照顾老人很细心', hidden: false, createdAt: '2026-05-05' },
    ],
    createdAt: '2026-02-20',
    updatedAt: '2026-05-15',
    resumeReviewStatus: 'approved',
  },
  {
    id: 'w003',
    name: '陈阿姨',
    age: 42,
    gender: '女',
    origin: '四川成都',
    photo: '',
    phone: '13700008901',
    idCard: '5101****9012',
    jobTypes: ['钟点工'],
    experienceYears: 3,
    specialties: ['做饭', '保洁'],
    certifications: [],
    expectedSalaryMin: 4000,
    expectedSalaryMax: 5500,
    status: 'paused',
    availableDate: '2026-06-20',
    creatorId: 'r001',
    creatorName: '刘芳',
    creatorRole: 'recruiter',
    creatorCommissionRate: 15,
    creditScore: 76,
    deposit: 0,
    points: 12,
    creditRecords: [
      { id: 'cr004', event: '中介费逾期', scoreChange: -3, createdAt: '2026-05-12' },
    ],
    trainingRecords: [],
    reviews: [],
    createdAt: '2026-04-01',
    updatedAt: '2026-05-12',
    resumeReviewStatus: 'pending',
  },
  {
    id: 'w004',
    name: '张玉梅',
    age: 50,
    gender: '女',
    origin: '河南郑州',
    photo: '',
    phone: '13600003456',
    idCard: '4101****3456',
    jobTypes: ['育儿嫂', '保姆'],
    experienceYears: 10,
    specialties: ['婴幼儿辅食', '早教启蒙', '家务'],
    certifications: ['高级育婴师证', '营养师证'],
    expectedSalaryMin: 10000,
    expectedSalaryMax: 13000,
    status: 'available',
    availableDate: '2026-06-01',
    creatorId: 'a001',
    creatorName: '张丽华',
    creatorRole: 'agent',
    creatorCommissionRate: 30,
    creditScore: 98,
    deposit: 500,
    points: 72,
    creditRecords: [
      { id: 'cr005', event: '获得客户好评', scoreChange: 2, createdAt: '2026-05-25' },
    ],
    trainingRecords: [],
    reviews: [
      { id: 'r005', type: 'customer', sourceRole: 'customer', reviewerName: '孙女士', reviewerRole: '客户', rating: 5, content: '育儿经验丰富，宝宝很喜欢', hidden: false, createdAt: '2026-05-25' },
    ],
    createdAt: '2026-01-15',
    updatedAt: '2026-05-25',
    resumeReviewStatus: 'approved',
  },
  {
    id: 'w005',
    name: '周小兰',
    age: 33,
    gender: '女',
    origin: '江西南昌',
    photo: '',
    phone: '13500007890',
    idCard: '3601****7890',
    jobTypes: ['月嫂'],
    experienceYears: 6,
    specialties: ['新生儿护理', '月子餐', '产后恢复'],
    certifications: ['高级月嫂证'],
    expectedSalaryMin: 14000,
    expectedSalaryMax: 18000,
    status: 'busy',
    availableDate: '2026-09-01',
    creatorId: 'a002',
    creatorName: '王建国',
    creatorRole: 'agent',
    creatorCommissionRate: 30,
    maintainerId: 'a001',
    maintainerName: '张丽华',
    maintainerCommissionRate: 10,
    creditScore: 92,
    deposit: 500,
    points: 55,
    creditRecords: [],
    trainingRecords: [
      { id: 'tr002', courseName: '月嫂技能进阶', instructorName: '李敏', score: 88, passed: true, completedAt: '2026-03-20' },
    ],
    reviews: [
      { id: 'r006', type: 'customer', sourceRole: 'customer', reviewerName: '何女士', reviewerRole: '客户', rating: 5, content: '月子餐做得特别好，宝宝照顾很专业', hidden: false, createdAt: '2026-05-10' },
    ],
    createdAt: '2026-02-01',
    updatedAt: '2026-05-20',
    resumeReviewStatus: 'approved',
  },
  {
    id: 'w006',
    name: '吴阿姨',
    age: 55,
    gender: '女',
    origin: '山东济南',
    photo: '',
    phone: '13300004567',
    idCard: '3701****4567',
    jobTypes: ['老人护理'],
    experienceYears: 7,
    specialties: ['卧床老人护理', '康复辅助', '做饭'],
    certifications: ['养老护理员证'],
    expectedSalaryMin: 8000,
    expectedSalaryMax: 10000,
    status: 'available',
    availableDate: '2026-06-10',
    creatorId: 'a003',
    creatorName: '赵明',
    creatorRole: 'agent',
    creatorCommissionRate: 30,
    creditScore: 82,
    deposit: 200,
    points: 28,
    creditRecords: [],
    trainingRecords: [],
    reviews: [],
    createdAt: '2026-04-20',
    updatedAt: '2026-05-18',
    resumeReviewStatus: 'rejected',
  },
];

// ==================== 经纪人/招生数据 ====================
export const mockAgents: AgentProfile[] = [
  {
    id: 'a001',
    name: '张丽华',
    phone: '13800001234',
    role: 'agent',
    reviewStatus: 'approved',
    experience: '5年家政行业经验',
    performance: '月均成交8单',
    creditScore: 96,
    deposit: 3000,
    points: 120,
    workerCount: 45,
    orderCount: 186,
    createdAt: '2026-01-01',
  },
  {
    id: 'a002',
    name: '王建国',
    phone: '13900005678',
    role: 'agent',
    reviewStatus: 'approved',
    experience: '3年家政经纪人经验',
    performance: '月均成交5单',
    creditScore: 90,
    deposit: 2000,
    points: 85,
    workerCount: 32,
    orderCount: 120,
    createdAt: '2026-02-15',
  },
  {
    id: 'a003',
    name: '赵明',
    phone: '13700009012',
    role: 'agent',
    reviewStatus: 'pending',
    experience: '2年家政行业经验，新转经纪人',
    performance: '新入驻',
    creditScore: 100,
    deposit: 0,
    points: 0,
    workerCount: 3,
    orderCount: 0,
    createdAt: '2026-05-20',
  },
  {
    id: 'r001',
    name: '刘芳',
    phone: '13600003456',
    role: 'recruiter',
    reviewStatus: 'approved',
    experience: '社区阿姨招募经验',
    performance: '月均招募5人',
    creditScore: 88,
    deposit: 800,
    points: 45,
    workerCount: 12,
    orderCount: 0,
    createdAt: '2026-03-01',
  },
  {
    id: 'r002',
    name: '孙小红',
    phone: '13500007890',
    role: 'recruiter',
    reviewStatus: 'pending',
    experience: '1年社区工作经验',
    performance: '新入驻',
    creditScore: 100,
    deposit: 0,
    points: 0,
    workerCount: 0,
    orderCount: 0,
    createdAt: '2026-05-25',
  },
  {
    id: 'ts001',
    name: '周主管',
    phone: '13200001111',
    role: 'training_supervisor',
    reviewStatus: 'approved',
    experience: '8年家政培训管理经验',
    performance: '管理10+招生，5+讲师',
    creditScore: 98,
    deposit: 5000,
    points: 200,
    workerCount: 0,
    orderCount: 0,
    createdAt: '2026-01-01',
  },
  {
    id: 'wo001',
    name: '杨运营',
    phone: '13200002222',
    role: 'worker_operator',
    reviewStatus: 'approved',
    experience: '5年阿姨运营管理经验',
    performance: '管理100+阿姨简历',
    creditScore: 95,
    deposit: 3000,
    points: 150,
    workerCount: 0,
    orderCount: 0,
    createdAt: '2026-01-01',
  },
];

// ==================== 讲师数据 ====================
export const mockInstructors: InstructorProfile[] = [
  {
    id: 'i001',
    name: '李敏',
    phone: '13800004567',
    reviewStatus: 'approved',
    qualifications: ['高级母婴护理师', '育婴师培训师'],
    creditScore: 94,
    deposit: 2000,
    points: 80,
    courseCount: 12,
    studentCount: 86,
    createdAt: '2026-01-10',
  },
  {
    id: 'i002',
    name: '陈老师',
    phone: '13900008901',
    reviewStatus: 'approved',
    qualifications: ['养老护理培训师', '急救培训师'],
    creditScore: 91,
    deposit: 1500,
    points: 60,
    courseCount: 8,
    studentCount: 52,
    createdAt: '2026-02-20',
  },
  {
    id: 'i003',
    name: '周婷',
    phone: '13700002345',
    reviewStatus: 'pending',
    qualifications: ['家政培训师'],
    creditScore: 100,
    deposit: 0,
    points: 0,
    courseCount: 0,
    studentCount: 0,
    createdAt: '2026-05-22',
  },
];

// ==================== 客户数据 ====================
export const mockCustomers: CustomerProfile[] = [
  { id: 'c001', name: '刘女士', phone: '13800001111', requirement: '需要月嫂，预产期7月', address: '朝阳区望京', creditScore: 95, orderCount: 3, createdAt: '2026-03-15' },
  { id: 'c002', name: '赵先生', phone: '13900002222', requirement: '老人护理，半自理', address: '海淀区中关村', creditScore: 90, orderCount: 2, createdAt: '2026-04-01' },
  { id: 'c003', name: '何女士', phone: '13700003333', requirement: '育儿嫂，带1岁宝宝', address: '西城区金融街', creditScore: 88, orderCount: 1, createdAt: '2026-05-10' },
  { id: 'c004', name: '孙女士', phone: '13600004444', requirement: '保姆，做饭家务', address: '丰台区方庄', creditScore: 92, orderCount: 4, createdAt: '2026-02-20' },
];

// ==================== 招生线索数据 ====================
export interface RecruiterLead {
  id: string;
  name: string;
  phone: string;
  age?: number;
  gender?: '女' | '男';
  origin?: string;
  intention?: string;
  level: 'A' | 'B' | 'C' | 'D'; // 线索等级
  source: string; // 来源
  status: LeadStatus; // 状态
  recruiterId: string;
  recruiterName: string;
  advisor?: string; // 招生顾问
  inPublicPool?: boolean; // 是否在公海库
  createdAt: string;
  remark: string;
}

export const mockRecruiterLeads: RecruiterLead[] = [
  { id: 'rl001', name: '小红', phone: '15812345678', age: 35, gender: '女', origin: '湖南', intention: '月嫂', level: 'A', source: '58同城', status: 'new', recruiterId: 'r001', recruiterName: '陈招生', createdAt: '2026-05-20', remark: '想做月嫂' },
  { id: 'rl002', name: '李姐', phone: '15900006789', age: 42, gender: '女', origin: '安徽', intention: '保姆', level: 'B', source: '转介绍', status: 'following', recruiterId: 'r001', recruiterName: '陈招生', createdAt: '2026-05-18', remark: '有经验，需培训升级' },
  { id: 'rl003', name: '王阿姨', phone: '15700007890', age: 45, gender: '女', origin: '四川', intention: '育儿嫂', level: 'B', source: '朋友圈', status: 'following', recruiterId: 'r001', recruiterName: '陈招生', createdAt: '2026-05-15', remark: '正在学育儿嫂课程' },
  { id: 'rl004', name: '张大姐', phone: '15600008901', age: 38, gender: '女', origin: '河南', intention: '钟点工', level: 'C', source: '线下推广', status: 'signed', recruiterId: 'r001', recruiterName: '陈招生', createdAt: '2026-05-10', remark: '已上户，客户满意' },
  { id: 'rl005', name: '刘阿姨', phone: '15500009012', age: 50, gender: '女', origin: '江西', intention: '保洁', level: 'D', source: '58同城', status: 'lost', recruiterId: 'r001', recruiterName: '陈招生', inPublicPool: true, createdAt: '2026-05-08', remark: '回老家了' },
  { id: 'rl006', name: '赵姐', phone: '13811112222', age: 33, gender: '女', origin: '湖北', intention: '月嫂', level: 'A', source: 'BOSS直聘', status: 'following', recruiterId: 'r002', recruiterName: '李招生', createdAt: '2026-05-22', remark: '想转行做月嫂' },
  { id: 'rl007', name: '孙大姐', phone: '13922223333', age: 46, gender: '女', origin: '山东', intention: '老人护理', level: 'C', source: '转介绍', status: 'lost', recruiterId: 'r002', recruiterName: '李招生', inPublicPool: true, createdAt: '2026-05-12', remark: '嫌远不想来了' },
];

// ==================== 订单数据 ====================
export const mockOrders: Order[] = [
  {
    id: 'o001',
    title: '需要月嫂一名',
    jobType: '月嫂',
    salaryMin: 12000,
    salaryMax: 15000,
    location: '朝阳区',
    description: '预产期7月，需要经验丰富的月嫂',
    agentId: 'a001',
    agentName: '张丽华',
    workerId: 'w001',
    workerName: '王秀兰',
    customerId: 'c001',
    customerName: '刘女士',
    status: 'signed',
    serviceFee: 3000,
    commissionRate: 20,
    createdAt: '2026-05-10',
    updatedAt: '2026-05-18',
    serviceType: '月嫂',
    amount: 15000,
    startDate: '2026-05-18',
    reviewed: false,
  },
  {
    id: 'o002',
    title: '住家保姆',
    jobType: '保姆',
    salaryMin: 7000,
    salaryMax: 9000,
    location: '海淀区',
    description: '需要照顾老人，会做饭',
    agentId: 'a002',
    agentName: '王建国',
    workerId: 'w002',
    workerName: '李大姐',
    customerId: 'c002',
    customerName: '赵先生',
    status: 'signed',
    serviceFee: 2000,
    commissionRate: 15,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-12',
    serviceType: '保姆',
    amount: 8000,
    startDate: '2026-05-12',
    reviewed: false,
  },
  {
    id: 'o003',
    title: '育儿嫂急需',
    jobType: '育儿嫂',
    salaryMin: 10000,
    salaryMax: 13000,
    location: '西城区',
    description: '1岁宝宝，需要育儿嫂全天照顾',
    agentId: 'a001',
    agentName: '张丽华',
    status: 'created',
    serviceFee: 0,
    commissionRate: 20,
    createdAt: '2026-05-25',
    updatedAt: '2026-05-25',
    serviceType: '育儿嫂',
    amount: 0,
    startDate: '',
    reviewed: false,
  },
  {
    id: 'o004',
    title: '钟点工每日3小时',
    jobType: '钟点工',
    salaryMin: 4000,
    salaryMax: 5000,
    location: '丰台区',
    description: '需要做饭+保洁',
    agentId: 'a002',
    agentName: '王建国',
    workerId: 'w003',
    workerName: '陈阿姨',
    status: 'interviewing',
    serviceFee: 800,
    commissionRate: 10,
    createdAt: '2026-05-20',
    updatedAt: '2026-05-22',
    serviceType: '钟点工',
    amount: 800,
    startDate: '2026-05-22',
    reviewed: false,
  },
  {
    id: 'o005',
    title: '老人护理住家',
    jobType: '老人护理',
    salaryMin: 8000,
    salaryMax: 10000,
    location: '通州区',
    description: '卧床老人，需要专业护理',
    agentId: 'a001',
    agentName: '张丽华',
    workerId: 'w006',
    workerName: '吴阿姨',
    customerId: 'c004',
    customerName: '孙女士',
    status: 'completed',
    serviceFee: 2500,
    commissionRate: 20,
    createdAt: '2026-04-01',
    updatedAt: '2026-05-01',
    serviceType: '老人护理',
    amount: 2500,
    startDate: '2026-04-01',
    reviewed: true,
  },
];

// ==================== 培训课程 ====================
export const mockCourses: TrainingCourse[] = [
  {
    id: 'tc001',
    name: '高级月嫂技能提升班',
    instructorId: 'i001',
    instructorName: '李敏',
    type: '技能提升',
    courseType: 'single' as const,
    maxStudents: 20,
    currentStudents: 15,
    startDate: '2026-06-01',
    endDate: '2026-06-15',
    price: 2800,
    hours: 40,
    location: '总部培训室A',
    status: 'upcoming',
    certificateOptions: ['月嫂证', '催乳师证'],
    createdAt: '2026-05-15',
  },
  {
    id: 'tc002',
    name: '新手月嫂入门班',
    instructorId: 'i001',
    instructorName: '李敏',
    type: '新手入行',
    courseType: 'single' as const,
    maxStudents: 15,
    currentStudents: 15,
    startDate: '2026-05-15',
    endDate: '2026-05-30',
    price: 1500,
    hours: 24,
    location: '总部培训室B',
    status: 'ongoing',
    certificateOptions: ['月嫂证'],
    createdAt: '2026-05-01',
  },
  {
    id: 'tc003',
    name: '养老护理专业培训',
    instructorId: 'i002',
    instructorName: '陈老师',
    type: '新手入行',
    courseType: 'single' as const,
    maxStudents: 20,
    currentStudents: 8,
    startDate: '2026-06-10',
    endDate: '2026-06-25',
    price: 1200,
    hours: 16,
    location: '分部培训室',
    status: 'upcoming',
    certificateOptions: ['护工证'],
    createdAt: '2026-05-20',
  },
  {
    id: 'tc004',
    name: '家政服务员基础班',
    instructorId: 'i002',
    instructorName: '陈老师',
    type: '新手入行',
    courseType: 'single' as const,
    maxStudents: 25,
    currentStudents: 25,
    startDate: '2026-04-15',
    endDate: '2026-04-30',
    price: 800,
    hours: 12,
    location: '总部培训室A',
    status: 'completed',
    certificateOptions: ['保姆证', '厨娘证'],
    createdAt: '2026-04-01',
  },
  {
    id: 'tc005',
    name: '高级育婴师认证班',
    instructorId: 'i001',
    instructorName: '李敏',
    type: '技能提升',
    courseType: 'single' as const,
    maxStudents: 18,
    currentStudents: 0,
    startDate: '2026-07-01',
    endDate: '2026-07-20',
    price: 3500,
    hours: 48,
    location: '总部培训室A',
    status: 'pending_approval',
    certificateOptions: ['育儿嫂证', '早教证'],
    createdAt: '2026-06-01',
  },
  {
    id: 'tc006',
    name: '保洁服务标准化培训',
    instructorId: 'i002',
    instructorName: '陈老师',
    type: '新手入行',
    courseType: 'single' as const,
    maxStudents: 30,
    currentStudents: 0,
    startDate: '2026-07-10',
    endDate: '2026-07-15',
    price: 600,
    hours: 8,
    location: '分部培训室',
    status: 'pending_approval',
    certificateOptions: ['保洁证'],
    createdAt: '2026-06-02',
  },
];

// ==================== 佣金规则 ====================
export const mockCommissionRules: CommissionRule[] = [
  {
    id: 'cm001',
    name: '服务费分账（同经纪人）',
    type: 'service_fee',
    description: '客户支付服务费，同一经纪人场景',
    rates: [
      { role: '签单经纪人', rate: 80, description: '签单经纪人分成' },
      { role: '平台', rate: 20, description: '平台分成' },
    ],
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'cm002',
    name: '服务费分账（跨经纪人）',
    type: 'service_fee',
    description: '客户支付服务费，跨经纪人场景',
    rates: [
      { role: '签单经纪人', rate: 80, description: '签单经纪人分成' },
      { role: '维护经纪人', rate: 8, description: '维护经纪人分成' },
      { role: '平台', rate: 12, description: '平台分成' },
    ],
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'cm003',
    name: '中介费分账',
    type: 'agency_fee',
    description: '阿姨支付中介费的分配',
    rates: [
      { role: '录入人', rate: 20, description: '招生/经纪人作为录入人' },
      { role: '维护人', rate: 30, description: '经纪人作为维护人' },
      { role: '推荐签单人', rate: 30, description: '推荐签单的经纪人' },
      { role: '平台', rate: 20, description: '平台分成' },
    ],
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'cm004',
    name: '培训费分账',
    type: 'training_fee',
    description: '培训费用的分配',
    rates: [
      { role: '平台', rate: 45, description: '平台分成' },
      { role: '讲师', rate: 20, description: '讲师授课提成' },
      { role: '谈单人', rate: 20, description: '谈单经纪人' },
      { role: '推荐人', rate: 15, description: '招生推荐提成' },
    ],
    active: true,
    createdAt: '2026-01-01',
  },
];

// ==================== 积分规则 ====================
export const mockPointRules: PointRule[] = [
  { id: 'pr001', action: '经纪人成交1单', points: 10, targetRole: 'agent', active: true },
  { id: 'pr002', action: '招生成功录入1个阿姨', points: 5, targetRole: 'recruiter', active: true },
  { id: 'pr003', action: '招生推荐阿姨参加培训', points: 8, targetRole: 'recruiter', active: true },
  { id: 'pr004', action: '讲师完成1期培训', points: 20, targetRole: 'instructor', active: true },
  { id: 'pr005', action: '阿姨获得客户好评', points: 3, targetRole: 'worker', active: true },
  { id: 'pr006', action: '阿姨完成培训', points: 10, targetRole: 'worker', active: true },
  { id: 'pr007', action: '经纪人跨经纪人协作', points: 5, targetRole: 'agent', active: true },
];

// ==================== 诚信分规则 ====================
export const mockCreditRules: CreditRule[] = [
  { id: 'clr001', event: '获得好评', scoreChange: 2, active: true },
  { id: 'clr002', event: '获得差评', scoreChange: -5, active: true },
  { id: 'clr003', event: '投诉成立', scoreChange: -10, active: true },
  { id: 'clr004', event: '违约/爽约', scoreChange: -15, active: true },
  { id: 'clr005', event: '中介费逾期', scoreChange: -3, active: true },
];

// ==================== 分账记录 ====================
export const mockSettlements: SettlementRecord[] = [
  {
    id: 's001',
    orderId: 'o001',
    type: 'service_fee',
    totalAmount: 3000,
    items: [
      { recipientId: 'a001', recipientName: '张丽华', recipientRole: '签单经纪人', amount: 2400, rate: 80 },
      { recipientId: 'platform', recipientName: '平台', recipientRole: '平台', amount: 600, rate: 20 },
    ],
    status: 'completed',
    createdAt: '2026-05-18',
  },
  {
    id: 's002',
    orderId: 'o005',
    type: 'agency_fee',
    totalAmount: 1500,
    items: [
      { recipientId: 'a001', recipientName: '张丽华', recipientRole: '维护人', amount: 450, rate: 30 },
      { recipientId: 'a001', recipientName: '张丽华', recipientRole: '推荐签单人', amount: 450, rate: 30 },
      { recipientId: 'a003', recipientName: '赵明', recipientRole: '录入人', amount: 300, rate: 20 },
      { recipientId: 'platform', recipientName: '平台', recipientRole: '平台', amount: 300, rate: 20 },
    ],
    status: 'completed',
    createdAt: '2026-05-01',
  },
];

// ==================== 合单大厅（经纪人/招生/讲师共享） ====================
// 合单大厅 = 其他经纪人发布的待匹配订单，三方都能推荐阿姨
export const mockHallOrders: Order[] = [
  {
    id: 'h001',
    title: '急需月嫂-预产期7月',
    jobType: '月嫂',
    salaryMin: 13000,
    salaryMax: 16000,
    location: '朝阳区望京',
    description: '预产期7月中旬，需要经验丰富月嫂，会催乳优先',
    agentId: 'a002',
    agentName: '王建国',
    status: 'created',
    serviceFee: 0,
    commissionRate: 20,
    createdAt: '2026-05-28',
    updatedAt: '2026-05-28',
  },
  {
    id: 'h002',
    title: '住家保姆照顾老人',
    jobType: '老人护理',
    salaryMin: 8000,
    salaryMax: 10000,
    location: '海淀区中关村',
    description: '70岁半自理老人，需住家保姆照顾，会做饭',
    agentId: 'a001',
    agentName: '张丽华',
    status: 'created',
    serviceFee: 0,
    commissionRate: 15,
    createdAt: '2026-05-27',
    updatedAt: '2026-05-27',
  },
  {
    id: 'h003',
    title: '育儿嫂-1岁宝宝',
    jobType: '育儿嫂',
    salaryMin: 10000,
    salaryMax: 12000,
    location: '西城区金融街',
    description: '1岁男宝，需要专业育儿嫂，会辅食制作',
    agentId: 'a002',
    agentName: '王建国',
    status: 'created',
    serviceFee: 0,
    commissionRate: 20,
    createdAt: '2026-05-26',
    updatedAt: '2026-05-26',
  },
  {
    id: 'h004',
    title: '双胞胎月嫂',
    jobType: '月嫂',
    salaryMin: 18000,
    salaryMax: 22000,
    location: '顺义区',
    description: '双胞胎预产期8月，需要有双胎经验的月嫂',
    agentId: 'a001',
    agentName: '张丽华',
    status: 'created',
    serviceFee: 0,
    commissionRate: 25,
    createdAt: '2026-05-25',
    updatedAt: '2026-05-25',
  },
  {
    id: 'h005',
    title: '钟点工-每日4小时',
    jobType: '钟点工',
    salaryMin: 4500,
    salaryMax: 6000,
    location: '丰台区方庄',
    description: '每天上午9-13点，做饭+保洁，3口之家',
    agentId: 'a002',
    agentName: '王建国',
    status: 'created',
    serviceFee: 0,
    commissionRate: 10,
    createdAt: '2026-05-24',
    updatedAt: '2026-05-24',
  },
];

// ==================== 推荐记录 ====================
export const mockReferrals: ReferralRecord[] = [
  {
    id: 'rf001',
    orderId: 'o001',
    orderTitle: '需要月嫂一名',
    workerId: 'w001',
    workerName: '王秀兰',
    referrerId: 'a001',
    referrerName: '张丽华',
    referrerRole: 'agent',
    commissionRate: 30,
    commissionAmount: 900,
    status: 'settled',
    settledAt: '2026-05-20',
    createdAt: '2026-05-10',
  },
  {
    id: 'rf002',
    orderId: 'o005',
    orderTitle: '老人护理住家',
    workerId: 'w006',
    workerName: '吴阿姨',
    referrerId: 'r001',
    referrerName: '刘芳',
    referrerRole: 'recruiter',
    commissionRate: 15,
    commissionAmount: 375,
    status: 'settled',
    settledAt: '2026-05-05',
    createdAt: '2026-04-01',
  },
  {
    id: 'rf003',
    orderId: 'h001',
    orderTitle: '急需月嫂-预产期7月',
    workerId: 'w004',
    workerName: '张玉梅',
    referrerId: 'a001',
    referrerName: '张丽华',
    referrerRole: 'agent',
    commissionRate: 30,
    commissionAmount: 0,
    status: 'pending',
    createdAt: '2026-05-28',
  },
  {
    id: 'rf004',
    orderId: 'h002',
    orderTitle: '住家保姆照顾老人',
    workerId: 'w002',
    workerName: '李大姐',
    referrerId: 'i001',
    referrerName: '李敏',
    referrerRole: 'instructor',
    commissionRate: 10,
    commissionAmount: 0,
    status: 'pending',
    createdAt: '2026-05-27',
  },
];

// 简历审核记录
export const mockResumeReviews: ResumeReviewRecord[] = [
  {
    id: 'rr1',
    workerId: 'w1',
    workerName: '王秀兰',
    type: 'update',
    changes: '修改了期望薪资(6000-8000→7000-9000)、新增证书"高级月嫂证"',
    submittedAt: '2026-05-28',
    reviewedAt: '2026-05-29',
    reviewerName: '管理员',
    reviewNote: '信息完整，审核通过',
    status: 'approved',
  },
  {
    id: 'rr2',
    workerId: 'w3',
    workerName: '赵玉梅',
    type: 'create',
    submittedAt: '2026-05-30',
    status: 'pending',
  },
  {
    id: 'rr3',
    workerId: 'w6',
    workerName: '陈小红',
    type: 'create',
    submittedAt: '2026-05-29',
    reviewedAt: '2026-05-30',
    reviewerName: '管理员',
    reviewNote: '身份证照片不清晰，请重新上传',
    status: 'rejected',
  },
  {
    id: 'rr4',
    workerId: 'w2',
    workerName: '李桂芬',
    type: 'update',
    changes: '修改了工种(新增"老人护理")、修改了自我介绍',
    submittedAt: '2026-05-31',
    status: 'pending',
  },
  {
    id: 'rr5',
    workerId: 'w4',
    workerName: '张美玲',
    type: 'create',
    submittedAt: '2026-05-27',
    reviewedAt: '2026-05-28',
    reviewerName: '管理员',
    reviewNote: '审核通过',
    status: 'approved',
  },
];

// 评价库 - 所有角色共用同一份数据
export const mockReviews: Review[] = [
  { id: 'r001', type: 'customer', sourceRole: 'customer', reviewerName: '刘女士', reviewerRole: '客户', rating: 5, content: '非常专业，照顾宝宝很细心', hidden: false, createdAt: '2026-05-18', targetId: 'w1', targetType: 'worker' },
  { id: 'r002', type: 'agent', sourceRole: 'agent', reviewerName: '张丽华', reviewerRole: '经纪人', rating: 4, content: '工作认真，客户反馈好', hidden: false, createdAt: '2026-05-15', targetId: 'w1', targetType: 'worker' },
  { id: 'r003', type: 'instructor', sourceRole: 'instructor', reviewerName: '李敏', reviewerRole: '讲师', rating: 5, content: '培训期间学习态度端正，技能掌握好', hidden: false, createdAt: '2026-04-15', targetId: 'w1', targetType: 'worker' },
  { id: 'r004', type: 'customer', sourceRole: 'customer', reviewerName: '赵先生', reviewerRole: '客户', rating: 4, content: '照顾老人很细心', hidden: false, createdAt: '2026-05-05', targetId: 'w2', targetType: 'worker' },
  { id: 'r005', type: 'customer', sourceRole: 'customer', reviewerName: '孙女士', reviewerRole: '客户', rating: 5, content: '育儿经验丰富，宝宝很喜欢', hidden: false, createdAt: '2026-05-25', targetId: 'w4', targetType: 'worker' },
  { id: 'r006', type: 'customer', sourceRole: 'customer', reviewerName: '何女士', reviewerRole: '客户', rating: 5, content: '月子餐做得特别好，宝宝照顾很专业', hidden: false, createdAt: '2026-05-10', targetId: 'w5', targetType: 'worker' },
  // 讲师评价
  { id: 'ir1', type: 'agent', sourceRole: 'agent', reviewerName: '张丽华', reviewerRole: '经纪人', rating: 5, content: '培训质量高，学员上手快', hidden: false, createdAt: '2025-01-14', targetId: 'inst1', targetType: 'instructor' },
  { id: 'ir2', type: 'recruiter', sourceRole: 'recruiter', reviewerName: '陈招生', reviewerRole: '招生', rating: 4, content: '推荐学员效果好', hidden: false, createdAt: '2025-01-10', targetId: 'inst1', targetType: 'instructor' },
  { id: 'ir3', type: 'worker', sourceRole: 'worker', reviewerName: '王秀兰', reviewerRole: '阿姨', rating: 5, content: '李老师讲课深入浅出', hidden: false, createdAt: '2025-01-06', targetId: 'inst1', targetType: 'instructor' },
  { id: 'ir4', type: 'worker', sourceRole: 'worker', reviewerName: '赵阿姨', reviewerRole: '阿姨', rating: 3, content: '课程节奏有点快', hidden: true, createdAt: '2025-01-02', targetId: 'inst1', targetType: 'instructor' },
];

// 招生线索签约转简历（2.0: 签约后自动创建worker，此函数仅用于mock回退）
export function convertLeadToResume(leadId: string): boolean {
  const lead = mockRecruiterLeads.find(l => l.id === leadId);
  if (lead && lead.status !== 'signed' && lead.status !== 'lost') {
    lead.status = 'signed';
    // 同步添加到阿姨库
    const newWorker: WorkerProfile = {
      id: `w_new_${Date.now()}`,
      name: lead.name,
      phone: lead.phone.includes('*') ? '13800000000' : lead.phone,
      age: lead.age || 35,
      gender: '女',
      origin: lead.origin || lead.source,
      photo: '',
      idCard: '',
      jobTypes: lead.intention ? [lead.intention as JobType] : ['保姆' as JobType],
      experienceYears: 0,
      specialties: [],
      certifications: [],
      expectedSalaryMin: 4000,
      expectedSalaryMax: 6000,
      status: 'pending',
      availableDate: '',
      creatorId: lead.recruiterId,
      creatorName: lead.recruiterName,
      creatorRole: 'recruiter',
      creatorCommissionRate: 30,
      maintainerId: lead.recruiterId,
      maintainerName: lead.recruiterName,
      maintainerCommissionRate: 10,
      referrerId: undefined,
      referrerName: undefined,
      referrerCommissionRate: undefined,
      creditScore: 1000,
      creditRecords: [],
      deposit: 0,
      points: 0,
      trainingRecords: [],
      reviews: [],
      resumeReviewStatus: 'pending',
      skills: [],
      remark: lead.remark || '',
      createdAt: new Date().toISOString().split('T')[0],
      updatedAt: new Date().toISOString().split('T')[0],
    };
    mockWorkers.push(newWorker);
    return true;
  }
  return false;
}

// ==================== 系统设置 ====================

const defaultPlatformInfo: PlatformInfo = {
  name: '家政共创平台',
  description: '连接阿姨、经纪人、招生代理、培训讲师和客户的多角色协作系统',
  contactPhone: '400-888-9999',
  contactEmail: 'admin@jiawu.com',
  phone: '400-888-9999',
  email: 'admin@jiawu.com',
  address: '安徽省合肥市',
  logoUrl: '',
  icpNumber: '',
};

const defaultModules: ModuleConfig[] = [
  // PC端模块
  { id: 'admin_dashboard', name: '仪表盘', label: '仪表盘', description: '全平台数据概览', enabled: true, category: 'pc' },
  { id: 'admin_reviews', name: '角色审核', label: '角色审核', description: '审核角色注册申请', enabled: true, category: 'pc' },
  { id: 'admin_resume_reviews', name: '简历审核', label: '简历审核', description: '审核阿姨简历', enabled: true, category: 'pc' },
  { id: 'admin_workers', name: '阿姨库管理', label: '阿姨库管理', description: '全平台阿姨管理', enabled: true, category: 'pc' },
  { id: 'admin_commission', name: '佣金配置', label: '佣金配置', description: '三级分账比例设置', enabled: true, category: 'pc' },
  { id: 'admin_settlement', name: '分账管理', label: '分账管理', description: '分账记录与结算', enabled: true, category: 'pc' },
  { id: 'admin_credit', name: '信用分管理', label: '信用分管理', description: '诚信分增减记录', enabled: true, category: 'pc' },
  { id: 'admin_deposit', name: '保证金管理', label: '保证金管理', description: '保证金缴纳/退还', enabled: true, category: 'pc' },
  { id: 'admin_refunds', name: '退款管理', label: '退款管理', description: '退款申请审批', enabled: true, category: 'pc' },
  { id: 'admin_points', name: '积分系统', label: '积分系统', description: '积分规则/记录', enabled: true, category: 'pc' },
  { id: 'admin_orders', name: '订单管理', label: '订单管理', description: '全平台订单', enabled: true, category: 'pc' },
  { id: 'admin_training', name: '培训管理', label: '培训管理', description: '课程/培训管理', enabled: true, category: 'pc' },
  { id: 'admin_recruitment', name: '招生管理', label: '招生管理', description: '招生线索管理', enabled: true, category: 'pc' },
  { id: 'admin_contracts', name: '合同管理', label: '合同管理', description: '合同审批/管理', enabled: true, category: 'pc' },
  { id: 'admin_venues', name: '场地管理', label: '场地管理', description: '培训场地管理', enabled: true, category: 'pc' },
  { id: 'admin_settings', name: '系统设置', label: '系统设置', description: '平台参数/规则/文字配置', enabled: true, category: 'pc' },
  // 小程序端模块
  { id: 'mini_worker_resume', name: '阿姨简历', label: '简历', description: '阿姨个人简历编辑', enabled: true, category: 'miniapp', role: 'worker', path: '/m/worker/resume' },
  { id: 'mini_worker_jobs', name: '接单大厅', label: '接单', description: '阿姨浏览可接订单', enabled: true, category: 'miniapp', role: 'worker', path: '/m/worker' },
  { id: 'mini_worker_reviews', name: '阿姨评价', label: '评价', description: '阿姨查看评价', enabled: true, category: 'miniapp', role: 'worker', path: '/m/worker/reviews' },
  { id: 'mini_agent_workers', name: '经纪人-阿姨管理', label: '阿姨', description: '经纪人管理阿姨', enabled: true, category: 'miniapp', role: 'agent', path: '/m/agent/workers' },
  { id: 'mini_agent_hall', name: '经纪人-合单大厅', label: '合单', description: '经纪人发单/合单', enabled: true, category: 'miniapp', role: 'agent', path: '/m/agent/orders' },
  { id: 'mini_recruiter_leads', name: '招生-线索跟进', label: '线索', description: '招生跟进线索', enabled: true, category: 'miniapp', role: 'recruiter', path: '/m/recruiter/follow' },
  { id: 'mini_recruiter_courses', name: '招生-课程推荐', label: '课程', description: '招生推荐课程', enabled: true, category: 'miniapp', role: 'recruiter', path: '/m/recruiter/courses' },
  { id: 'mini_instructor_courses', name: '讲师-课程教学', label: '课程', description: '讲师教学管理', enabled: true, category: 'miniapp', role: 'instructor', path: '/m/instructor/follow' },
  { id: 'mini_instructor_leads', name: '讲师-线索跟进', label: '线索', description: '讲师跟进学员', enabled: true, category: 'miniapp', role: 'instructor', path: '/m/instructor/workers' },
  { id: 'mini_ts_leads', name: '培训主管-线索管理', label: '线索', description: '管理所有招生线索', enabled: true, category: 'miniapp', role: 'training_supervisor', path: '/m/training_supervisor/leads' },
  { id: 'mini_ts_courses', name: '培训主管-课程审批', label: '课程', description: '课程审批管理', enabled: true, category: 'miniapp', role: 'training_supervisor', path: '/m/training_supervisor/courses' },
  { id: 'mini_ts_contracts', name: '培训主管-合同审批', label: '合同', description: '合同审批管理', enabled: true, category: 'miniapp', role: 'training_supervisor', path: '/m/training_supervisor/approval/contracts' },
  { id: 'mini_wo_workers', name: '阿姨运营-阿姨列表', label: '阿姨', description: '管理阿姨简历库', enabled: true, category: 'miniapp', role: 'worker_operator', path: '/m/worker_operator/workers' },
  { id: 'mini_wo_hall', name: '阿姨运营-合单大厅', label: '合单', description: '推荐阿姨合单', enabled: true, category: 'miniapp', role: 'worker_operator', path: '/m/worker_operator/hall' },
];

const defaultCommissionRules: CommissionRule[] = [
  { id: 'cr1', name: '服务费佣金', type: 'service_fee', description: '服务订单佣金分配', rates: [{ role: '经纪人', rate: 40, description: '经纪人分佣' }, { role: '招生代理', rate: 15, description: '招生代理分佣' }, { role: '平台', rate: 45, description: '平台服务费' }], active: true, createdAt: '2026-01-01' },
  { id: 'cr2', name: '中介费佣金', type: 'agency_fee', description: '中介订单佣金分配', rates: [{ role: '经纪人', rate: 35, description: '经纪人分佣' }, { role: '招生代理', rate: 10, description: '招生代理分佣' }, { role: '平台', rate: 55, description: '平台服务费' }], active: true, createdAt: '2026-01-01' },
  { id: 'cr3', name: '培训费佣金', type: 'training_fee', description: '培训订单佣金分配', rates: [{ role: '经纪人', rate: 30, description: '经纪人分佣' }, { role: '招生代理', rate: 10, description: '招生代理分佣' }, { role: '平台', rate: 60, description: '平台服务费' }], active: true, createdAt: '2026-01-01' },
];

const defaultPointRules: PointRule[] = [
  { id: 'pr1', action: '完成订单', points: 50, targetRole: 'worker' as Role, active: true },
  { id: 'pr2', action: '获得好评', points: 20, targetRole: 'worker' as Role, active: true },
  { id: 'pr3', action: '完成培训', points: 30, targetRole: 'worker' as Role, active: true },
  { id: 'pr4', action: '推荐新人', points: 40, targetRole: 'agent' as Role, active: true },
  { id: 'pr5', action: '录入线索', points: 10, targetRole: 'recruiter' as Role, active: true },
  { id: 'pr6', action: '违约扣分', points: -100, targetRole: 'worker' as Role, active: true },
  { id: 'pr7', action: '迟到扣分', points: -20, targetRole: 'worker' as Role, active: true },
];

const defaultCreditRules: CreditRule[] = [
  { id: 'clr1', event: '完成订单', scoreChange: 5, active: true },
  { id: 'clr2', event: '获得好评', scoreChange: 3, active: true },
  { id: 'clr3', event: '违约', scoreChange: -20, active: true },
  { id: 'clr4', event: '无故旷工', scoreChange: -15, active: true },
  { id: 'clr5', event: '完成培训', scoreChange: 5, active: true },
];

const defaultTexts: TextConfig[] = [
  { id: 'txt1', key: 'platform_name', label: '平台名称', value: '家政共创平台', group: '平台', category: '平台' },
  { id: 'txt2', key: 'platform_slogan', label: '平台标语', value: '专业家政服务，诚信共创未来', group: '平台', category: '平台' },
  { id: 'txt3', key: 'worker_label', label: '阿姨称呼', value: '阿姨', group: '角色', category: '角色' },
  { id: 'txt4', key: 'agent_label', label: '经纪人称呼', value: '经纪人', group: '角色', category: '角色' },
  { id: 'txt5', key: 'recruiter_label', label: '招生称呼', value: '招生', group: '角色', category: '角色' },
  { id: 'txt6', key: 'instructor_label', label: '讲师称呼', value: '讲师', group: '角色', category: '角色' },
  { id: 'txt7', key: 'customer_label', label: '客户称呼', value: '客户', group: '角色', category: '角色' },
  { id: 'txt8', key: 'lead_label', label: '线索称呼', value: '线索', group: '模块', category: '模块' },
  { id: 'txt9', key: 'student_label', label: '学员称呼', value: '学员', group: '模块', category: '模块' },
  { id: 'txt10', key: 'hall_label', label: '合单大厅称呼', value: '合单大厅', group: '模块', category: '模块' },
  { id: 'txt11', key: 'credit_label', label: '诚信分称呼', value: '诚信分', group: '模块', category: '模块' },
  { id: 'txt12', key: 'deposit_label', label: '保证金称呼', value: '保证金', group: '模块', category: '模块' },
  { id: 'txt13', key: 'welcome_text', label: '欢迎语', value: '欢迎使用家政共创平台', group: '平台', category: '平台' },
  { id: 'txt14', key: 'credit_check_tip', label: '征信查询提示', value: '征信查询结果仅供参考，如有疑义请反馈核实', group: '模块', category: '模块' },
];

export const systemSettings: SystemSettings = {
  platformInfo: defaultPlatformInfo,
  commissionRules: defaultCommissionRules,
  pointRules: defaultPointRules,
  creditRules: defaultCreditRules,
  modules: defaultModules,
  texts: defaultTexts,
};