-- 订单签约字段补全（幂等）
ALTER TABLE orders ADD COLUMN IF NOT EXISTS worker_salary INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS commission INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS contract_start_date DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS contract_end_date DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS signing_notes TEXT;
